#!/bin/bash

if [ "$1" == "up" ]; then
  amixer set Master 2%+ unmute
elif [ "$1" == "down" ]; then
  amixer set Master 2%- unmute
elif [ "$1" == toggle ]; then
  amixer set Master toggle
fi

pkill --signal SIGRTMIN+1 i3blocks
